### ISSUE TITLE
req

### ISSUE THREAD

**Issue by techwiz37** [VEXG/cilok-v2-md#3]
req gan ngecek apakah pesan itu dikirim dari baileys atau bukan. aku coba gini eror

proto.baileys = mel.key?.id && mel.key?.id?.length === 16 || mel.key?.id?.startsWith("3EB0") && mel.key?.id.length === 12 || false;

kode sc sblh gitu, aku coba bikin eror

**Comment by Xevalous** [comment]
`mess.key?.id ? mess.key.id <= 16 || mess.key.id.startsWith("3EB0")  : false`

Tolong di ingat gak semua base / source code bot wa sama. So please jangan asal tempel-tempel aja ;)
